# Generated by Django 4.1.1 on 2022-10-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plato', '0001_initial'),
        ('Pedido', '0003_pedido_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='platos',
            field=models.ManyToManyField(to='Plato.plato'),
        ),
    ]
