# Generated by Django 4.1.1 on 2022-10-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0004_pedido_platos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='horaEntregaDesde',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='horaEntregaHasta',
            field=models.TimeField(),
        ),
    ]
