# Generated by Django 4.1.1 on 2022-10-30 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadete', '0002_alter_cadete_patentevehiculo'),
        ('Pedido', '0005_alter_pedido_horaentregadesde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Cadete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cadete.cadete'),
        ),
    ]
