# Generated by Django 4.1.1 on 2022-11-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0006_pedido_cadete'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comentario',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
