# Generated by Django 4.1.1 on 2022-10-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadete',
            name='patenteVehiculo',
            field=models.CharField(max_length=9),
        ),
    ]
