# Generated by Django 4.1.1 on 2022-10-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='localidad',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cuil',
            field=models.DecimalField(decimal_places=0, max_digits=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
