# Generated by Django 4.1.1 on 2022-10-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0002_alter_direccion_localidad_alter_persona_cuil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.CharField(max_length=5),
        ),
    ]
