# Generated by Django 4.1.1 on 2022-10-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuil', models.DecimalField(decimal_places=0, max_digits=8, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('sexo', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='F', max_length=1)),
            ],
        ),
    ]
