# Generated by Django 4.1.1 on 2022-10-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
