# Generated by Django 4.1.1 on 2022-10-22 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plato', '0001_initial'),
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plato',
            new_name='TipoPlato',
        ),
    ]
