# Generated by Django 4.1.1 on 2022-10-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_rename_plato_tipoplato'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='tipoMenu',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Celíaco', 'Celíaco'), ('Vegetariano', 'Vegetariano'), ('Diabético', 'Diabético')], default='Normal', max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='tipoplato',
            name='tipoPlato',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Plato principal', 'Plato principal'), ('Postre', 'Postre')], default='Entrada', max_length=16, unique=True),
        ),
    ]
