# Generated by Django 4.1.1 on 2022-10-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plato', '0003_rename_tipoplato_plato_tipo_plato'),
        ('Menu', '0003_menu_tipomenu_tipoplato_tipoplato'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoPlato',
            new_name='Tipo_Plato',
        ),
    ]
