# Generated by Django 4.1.1 on 2022-10-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plato', '__first__'),
        ('Menu', '0004_rename_tipoplato_tipo_plato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_plato',
            old_name='tipoPlato',
            new_name='opcionPlato',
        ),
    ]
