# Generated by Django 4.1.1 on 2022-10-23 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcionPlato', models.CharField(max_length=200)),
                ('activo', models.BooleanField()),
                ('Menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Menu.menu')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPlato', models.CharField(choices=[('Entrada', 'Entrada'), ('Plato principal', 'Plato principal'), ('Postre', 'Postre')], default='Entrada', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fechaActualizacionPrecio', models.DateField()),
                ('codigoPlato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Plato.plato')),
            ],
        ),
        migrations.AddField(
            model_name='plato',
            name='Precio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Plato.precio'),
        ),
        migrations.AddField(
            model_name='plato',
            name='TipoPlato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Plato.tipoplato'),
        ),
    ]
