# Generated by Django 4.1.1 on 2022-10-25 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plato', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precio',
            old_name='codigoPlato',
            new_name='Plato',
        ),
    ]
