# Generated by Django 4.1.1 on 2022-10-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plato', '0002_rename_tipomenu_plato_menu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plato',
            old_name='TipoPlato',
            new_name='Tipo_Plato',
        ),
    ]
