# Generated by Django 4.1.1 on 2022-10-22 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0005_rename_tipoplato_tipo_plato_opcionplato'),
        ('Plato', '0003_rename_tipoplato_plato_tipo_plato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='Menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Menu.menu'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='Precio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Plato.precio'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='Tipo_Plato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Menu.tipo_plato'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='codigoPlato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Plato.plato'),
        ),
    ]
