# Generated by Django 4.1.1 on 2022-10-22 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pedido', '0002_tipoentrega_estado_estadopedido_pedido_estado_and_more'),
        ('Menu', '0003_menu_tipomenu_tipoplato_tipoplato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vianda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaVigencia', models.DateField()),
                ('tipoEntregaVianda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedido.tipoentrega')),
                ('tipoVianda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.menu')),
            ],
        ),
    ]
