# Generated by Django 4.1.1 on 2022-10-25 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
        ('Vianda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vianda',
            name='Cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente'),
        ),
    ]
